on:
  pull_request:
    branches: [main]
    types: [closed]
jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - # create a build kit builder instance
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          target: development
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME}}/nestjs-source-template:latest
          